/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 ./public/Models/CClass/CClass.gltf -r public
Author: RADEONGAMER (https://sketchfab.com/RADEONGAMER)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mercedes-benz-amg-cls-4ef108f906e84bcaa3e66bed9b4cef9f
Title: Mercedes-Benz AMG CLS
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useEffect } from 'react'
import { Mesh } from 'three'

export function BenzJSX(props) {
  const { nodes, materials } = useGLTF('/Models/CClass/CClass.gltf');

  const gltf = useLoader(GLTFLoader, "Models/CClass/CClass.gltf")

  useEffect(() => {
      gltf.scene.scale.set(10.7, 10.7, 10.7);
      gltf.scene.position.set(0, 0.01, 0);

      gltf.scene.traverse((object) => {
          if (object instanceof Mesh) {
              object.castShadow = true;
              object.receiveShadow = true;
              object.material.envMapIntensity = 20;
          }
      })
  }, [gltf])

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESHdMESH_MESH0MESH5MESH_MES_silver_d_0.geometry} material={materials.silver_d} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH2MES_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH1MES_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH002_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH2MESH5MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH003_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHgMESHlMESHaMESHsMESHsMESH_MESH0MESH4MESH_MESHgMESHlMESHaMES_glass_0.geometry} material={materials.glass} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH2MESH3MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESH0MESH4MESH_MESHbMESHlMESHaMES_black_0.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH2MESH0MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH1MESH9MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHdMESH_MESHgMESHlMESHaMESHsMESHsMESH_MESH0MESH2MESH_MESHdMES_d_glass_0.geometry} material={materials.d_glass} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESHdMESH_MESH0MESH3MESH_MES_silver_d_0.geometry} material={materials.silver_d} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESHdMESH_MESH0MESH1MESH_MES_silver_d_0.geometry} material={materials.silver_d} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESH1MESH0MESH_MESHsMESHiMES_silver_0.geometry} material={materials.silver} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH005_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHsMESHhMESHiMESHnMESHyMESH_MES_black_shiny_0.geometry} material={materials.black_shiny} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHgMESHlMESHaMESHsMESHsMESH_MESH0MESH1MESH_MESHgMESHlMESHaMES_glass_0.geometry} material={materials.glass} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHsMESHhMESHiMESHnMESHyMESH_black_shiny_0.geometry} material={materials.black_shiny} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH1MESH4MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESH0MESH8MESH_MESHsMESHiMES_silver_0.geometry} material={materials.silver} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHsMESHhMESHiMESHnMESHyMESH002_black_shiny_0.geometry} material={materials.black_shiny} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHtMESHiMESHrMESHeMESH_MESHmMESHaMESHtMESH5MESH_MESH0MESH3MES_tire_mat5_0.geometry} material={materials.tire_mat5} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHrMESHaMESHkMESHeMESHsMESH2MESH_MESH0MESH3MESH_MESHbMES_brakes2_0.geometry} material={materials.brakes2} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH007_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHoMESHdMESHyMESH_MESH0MESH7MESH_MESHbMESHoMESHdMESHyMES_body_0.geometry} material={materials.body} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESHdMESH_MESH0MESH6MESH_MES_silver_d_0.geometry} material={materials.silver_d} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHsMESHhMESHiMESHnMESHyMESH004_black_shiny_0.geometry} material={materials.black_shiny} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHrMESHaMESHkMESHeMESHsMESH2MESH_MESH0MESH1MESH_MESHbMES_brakes2_0.geometry} material={materials.brakes2} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH008_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHdMESH_MESHgMESHlMESHaMESHsMESHsMESH_MESH0MESH1MESH_MESHdMES_d_glass_0.geometry} material={materials.d_glass} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHtMESHiMESHrMESHeMESH_MESHmMESHaMESHtMESH5MESH_MESH0MESH2MES_tire_mat5_0.geometry} material={materials.tire_mat5} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHtMESHiMESHrMESHeMESH_MESHmMESHaMESHtMESH5MESH_MESH0MESH1MES_tire_mat5_0.geometry} material={materials.tire_mat5} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESH0MESH4MESH_MESHsMESHiMES_silver_0.geometry} material={materials.silver} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHoMESHdMESHyMESH_MESH0MESH1MESH_MESHbMESHoMESHdMESHyMES_body_0.geometry} material={materials.body} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHpMESHlMESHaMESHtMESHeMESH_MESH0MESH1MESH_MESHpMESHlMESHaMES_plate_0.geometry} material={materials.plate} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH0MESH3MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH0MESH1MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESH0MESH2MESH_MESHsMESHiMES_silver_0.geometry} material={materials.silver} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHsMESHhMESHiMESHnMESHyMESH008_black_shiny_0.geometry} material={materials.black_shiny} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH1MESH2MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESH0MESH6MESH_MESHsMESHiMES_silver_0.geometry} material={materials.silver} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH010_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHoMESHdMESHyMESH_MESH0MESH2MESH_MESHbMESHoMESHdMESHyMES_body_0.geometry} material={materials.body} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH013_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESH1MESH6MESH_MESHsMESHiMES_silver_0.geometry} material={materials.silver} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHpMESHlMESHaMESHtMESHeMESH_MESH0MESH2MESH_MESHpMESHlMESHaMES_plate_0.geometry} material={materials.plate} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHiMESHnMESHtMESHeMESHrMESHiMESHoMESHrMESH_MESH0MESH1MESH_MES_interior_0.geometry} material={materials.interior} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESH1MESH5MESH_MESHsMESHiMES_silver_0.geometry} material={materials.silver} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHrMESHeMESHdMESH_MESH0MESH1MESH_MESHrMESHeMESHdMESH_MESH0MES_red_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHoMESHdMESHyMESH_MESH0MESH5MESH_MESHbMESHoMESHdMESHyMES_body_0.geometry} material={materials.body} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHoMESHdMESHyMESH_MESH0MESH4MESH_MESHbMESHoMESHdMESHyMES_body_0.geometry} material={materials.body} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH0MESH5MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHsMESHhMESHiMESHnMESHyMESH011_black_shiny_0.geometry} material={materials.black_shiny} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHsMESHhMESHiMESHnMESHyMESH012_black_shiny_0.geometry} material={materials.black_shiny} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH1MESH0MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHsMESHhMESHiMESHnMESHyMESH014_black_shiny_0.geometry} material={materials.black_shiny} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH016_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESH0MESH3MESH_MESHbMESHlMESHaMES_black_0.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH0MESH8MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH018_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHbMESHlMESHaMESHcMESHkMESH_MESHmMESHaMESHtMESHtMESH_MESH019_black_matt_0.geometry} material={materials.black_matt} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHsMESHiMESHlMESHvMESHeMESHrMESH_MESH1MESH1MESH_MESHsMESHiMES_silver_0.geometry} material={materials.silver} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
          <mesh geometry={nodes.MESHcMESHhMESHrMESHoMESHmMESHeMESH_MESH1MESH8MESH_MESHcMESHhMES_chrome_0.geometry} material={materials.chrome} rotation={[-Math.PI / 2, 0, 0]} scale={50} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/CClass/CClass.gltf')
