/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: abhinavislive643 (https://sketchfab.com/abhinavislive643)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/g-wagon-5921d829f1bd412eb07296ecb7cac372
title: G-wagon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GWagon6x6(props) {
  const { nodes, materials } = useGLTF('/Models/GWagon6x6/GWagon6x6.gltf')
  return (
    <group {...props} dispose={null} scale={1} position={[2,0,-2]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group position={[192.69, -268.78, 70.62]} rotation={[1.27, 0.82, 0.22]} />
        <mesh geometry={nodes.Material2.geometry} material={materials.Second_Body_Col} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.Second_Body_Col} />
        <mesh geometry={nodes.Material3.geometry} material={materials.extra_details_carcoal} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.extra_details_carcoal} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials.extra_details_carcoal} />
        <mesh geometry={nodes.Material3_3.geometry} material={materials.extra_details_carcoal} />
        <mesh geometry={nodes.Material3_4.geometry} material={materials.Body_Col} />
        <mesh geometry={nodes.Material3_5.geometry} material={materials.Material__438} />
        <lineSegments geometry={nodes.Material2_2.geometry} material={materials.edge_color000255} />
        <mesh geometry={nodes.Material3_6.geometry} material={materials.Material__544} />
        <mesh geometry={nodes.Material3_7.geometry} material={materials.Light_Col} />
        <mesh geometry={nodes.Material3_8.geometry} material={materials.Material__445} />
        <mesh geometry={nodes.Material3_9.geometry} material={materials.Material__470} />
        <mesh geometry={nodes.Material3_10.geometry} material={materials.Material__526} />
        <mesh geometry={nodes.Material3_11.geometry} material={materials.Material__452} />
        <mesh geometry={nodes.Material3_12.geometry} material={materials.Material__469} />
        <mesh geometry={nodes.Material3_13.geometry} material={materials.Material__464} />
        <mesh geometry={nodes.Material3_14.geometry} material={materials.Material__463} />
        <mesh geometry={nodes.Material3_15.geometry} material={materials.Material__507} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.Color_001} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.Color_001} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Color_006} />
        <mesh geometry={nodes.Material3_16.geometry} material={materials.Color_009} />
        <mesh geometry={nodes.Material3_17.geometry} material={materials.Color_A16} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.tire} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.tire} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials.tire} />
        <lineSegments geometry={nodes.Material2_9.geometry} material={materials.edge_color202020255} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/GWagon6x6/GWagon6x6.gltf')
