/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 ./public/Models/Mclaren/Mclaren.gltf -r public
Author: _Sheep19 (https://sketchfab.com/shobhit190401)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2017-mclaren-720s-f7bece69400f4640a4a3be746b44998b
Title: 2017 Mclaren 720s
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useEffect } from 'react'
import { Mesh } from 'three'

export function MclarenJSX(props) {
  const gltf = useLoader(GLTFLoader, "Models/Mclaren/Mclaren.gltf")

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Models/Mclaren/Mclaren.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    gltf.scene.scale.set(1.2, 1.2, 1.2);

    gltf.scene.position.set(0, 0.01, 0);
    gltf.scene.traverse((object) => {
        if (object instanceof Mesh) {
            object.castShadow = true;
            object.receiveShadow = true;
            object.material.envMapIntensity = 20;

        }
    })
}, [gltf])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2 , 0, -Math.PI / 2]}>
          <group name="2a155029ec974ab992b4b3a5c4a6eac3fbx" rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="spoiler" position={[111, 56.35, -0.05]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="spoiler_body_0" geometry={nodes.spoiler_body_0.geometry} material={materials.body} />
                  <mesh name="spoiler_silver_0" geometry={nodes.spoiler_silver_0.geometry} material={materials.silver} />
                  <mesh name="spoiler_lights_0" geometry={nodes.spoiler_lights_0.geometry} material={materials.lights} />
                </group>
                <group name="tyres" position={[-81.79, 22.37, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="tyres_tyres_0" geometry={nodes.tyres_tyres_0.geometry} material={materials.tyres} />
                  <mesh name="tyres_rims_0" geometry={nodes.tyres_rims_0.geometry} material={materials.rims} />
                </group>
                <group name="tyres001" position={[98.32, 22.83, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="tyres001_tyres_0" geometry={nodes.tyres001_tyres_0.geometry} material={materials.tyres} />
                  <mesh name="tyres001_rims_0" geometry={nodes.tyres001_rims_0.geometry} material={materials.rims} />
                </group>
                <group name="body" position={[0, 0.21, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="body_carbon_fibre_0" geometry={nodes.body_carbon_fibre_0.geometry} material={materials.carbon_fibre} />
                  <mesh name="body_body_0" geometry={nodes.body_body_0.geometry} material={materials.body} />
                  <mesh name="body_black_metallic_0" geometry={nodes.body_black_metallic_0.geometry} material={materials.black_metallic} />
                  <mesh name="body_mesh_0" geometry={nodes.body_mesh_0.geometry} material={materials.mesh} />
                  <mesh name="body_lights_0" geometry={nodes.body_lights_0.geometry} material={materials.lights} />
                  <mesh name="body_glass_0" geometry={nodes.body_glass_0.geometry} material={materials.glass} />
                  <mesh name="body_silver_0" geometry={nodes.body_silver_0.geometry} material={materials.silver} />
                </group>
                <group name="side_mirrors" position={[0, 0.21, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="side_mirrors_body_0" geometry={nodes.side_mirrors_body_0.geometry} material={materials.body} />
                  <mesh name="side_mirrors_carbon_fibre_0" geometry={nodes.side_mirrors_carbon_fibre_0.geometry} material={materials.carbon_fibre} />
                  <mesh name="side_mirrors_mirror_0" geometry={nodes.side_mirrors_mirror_0.geometry} material={materials.mirror} />
                </group>
                <group name="windows" position={[0, 0.21, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="windows_glass_0" geometry={nodes.windows_glass_0.geometry} material={materials.glass} />
                  <mesh name="windows_black_metallic_0" geometry={nodes.windows_black_metallic_0.geometry} material={materials.black_metallic} />
                </group>
                <group name="interior001" position={[8.94, -1.09, -0.01]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={67.56}>
                  <mesh name="interior001_interior_0" geometry={nodes.interior001_interior_0.geometry} material={materials.interior} />
                  <mesh name="interior001_mirror_0" geometry={nodes.interior001_mirror_0.geometry} material={materials.mirror} />
                </group>
                <group name="badges" position={[146.29, 45.48, 0]} rotation={[-Math.PI / 2, 1.52, Math.PI / 2]} scale={[6.74, 1.15, 1.15]}>
                  <mesh name="badges_badges_0" geometry={nodes.badges_badges_0.geometry} material={materials.badges} />
                </group>
                <group name="brake_dics_and_caps" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="brake_dics_and_caps_brake_dics_and_caps_0" geometry={nodes.brake_dics_and_caps_brake_dics_and_caps_0.geometry} material={materials.brake_dics_and_caps} />
                </group>
                <group name="wipers" position={[-696.76, -5.66, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.69}>
                  <mesh name="wipers_black_metallic_0" geometry={nodes.wipers_black_metallic_0.geometry} material={materials.black_metallic} />
                </group>
                <group name="interior" position={[8.94, -1.09, -0.01]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={67.56}>
                  <mesh name="interior_interior_A_0" geometry={nodes.interior_interior_A_0.geometry} material={materials.interior_A} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Mclaren/Mclaren.gltf')
