/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Artise1 (https://sketchfab.com/Artise1)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/water-animation-e54ff76bef854b128af8d20cf9c03729
title: Water Animation
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function WaterAnimations(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Models/WaterAnimation/WaterAnimation.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
actions?.["Take 001"].play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="e179be81fa0a492eb2ed52be822eb2c2fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Water_Export" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="0" geometry={nodes['0'].geometry} material={materials['Scene_-_Root']} morphTargetDictionary={nodes['0'].morphTargetDictionary} morphTargetInfluences={nodes['0'].morphTargetInfluences} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/WaterAnimation/WaterAnimation.gltf')
