import { Loader, PerspectiveCamera, Stats } from '@react-three/drei'
import Head from 'next/head'
import React, { useRef, useState } from 'react'
// Components
import CarScene from './Components/Car'

// @react-three/fiber
import { Canvas } from '@react-three/fiber'


const Home = () => {

  const [hasMounted, setHasMounted] = React.useState(false);

  React.useEffect(() => {
    setHasMounted(true);
  }, []);


  return (
    <div className={`h-full min-h-screen w-full grid grid-cols-[repeat(7,1fr)] grid-rows-[50px,800px,50px] bg-[black]`}>
      <Head>
        <title> three Animations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`col-start-1 col-end-8 row-start-2 `}>
        {hasMounted && (
          <React.Fragment>
            <CarScene />
            <Loader />
          </React.Fragment>
        )}

      </div>

    </div>
  )
}


export default Home;